### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by adamreed90** [Azure/Microsoft.Extensions.Caching.Cosmos#12]
Is this Production Ready? Will there be a nuget release?

**Comment by ealsur** [comment]
Yes, it's production ready. We are working on a Nuget release, no ETA yet, but I'll try share more info as I have it.

If you do run into any issues, please report them here.

**Comment by ealsur** [comment]
We have added a section on README regarding account Consistency that would be important to consider https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos#cosmos-account-consistency

**Comment by ericsampson** [comment]
It would be very handy to have a NuGet package published for this. Thanks Matias!

**Comment by ealsur** [comment]
I agree and looking on it 😄 The more +1s this Issue gets, the better to push it 😉

**Comment by toivs03** [comment]
Yes please, a NuGet package would be wonderful :)

**Comment by adamreed90** [comment]
We would love to take this into an upcoming product for production, extending this past Session Caching and as an override to a MemoryCache is something we are also considering, but really would love to see this get to NuGet! 👍

**Comment by ealsur** [comment]
Working on it, ETA is one-two weeks to have a package out. Maybe less.

**Comment by ealsur** [comment]
Nuget is available https://www.nuget.org/packages/Microsoft.Extensions.Caching.Cosmos/1.0.0-preview

**Comment by adamreed90** [comment]
Thanks @ealsur!
