### ISSUE TITLE
CreateIfNotExists does not appear to set indexing options as described.

### ISSUE THREAD

**Issue by ericsampson** [Azure/Microsoft.Extensions.Caching.Cosmos#14]
We used the CreateIfNotExists option and the resulting container has the following indexing options set, which is not what was described in the documentation (or code) in terms of effectively disabling indexing:
`{
    "indexingMode": "consistent",
    "automatic": true,
    "includedPaths": [
        {
            "path": "/*"
        }
    ],
    "excludedPaths": [
        {
            "path": "/\"_etag\"/?"
        }
    ]
}`
Thanks in advance!

**Comment by ealsur** [comment]
@ericsampson Are you sure the container does not previously exist?

[One of the Tests](https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/tests/emulator/CosmosCacheEmulatorTests.cs#L36) create the container and running it creates it with this Indexing Policy:

![image](https://user-images.githubusercontent.com/1633401/71738194-c6517800-2e0a-11ea-8006-b21d0fa6ac0c.png)


Which is the expected one.

**Comment by ealsur** [comment]
[CreateIfNotExists](https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/src/CosmosCache.cs#L296) won't update or change an existing container, so if you are creating it previously as part of the initialization of the application, it won't overwrite it.

**Comment by ericsampson** [comment]
@ealsur the developer who worked on the project swore that the container was brand new, so I took him at his word. I'll double check with a temp one to see if something was lost in translation, and then report back. Thanks!

**Comment by ealsur** [comment]
@ericsampson I'm closing this issue as not able to repro. But please reopen it if you have further evidence or a way to replicate.

**Comment by ericsampson** [comment]
sounds good.
