### ISSUE TITLE
Make ReplaceItem call optional

### ISSUE THREAD

**Issue by krispenner** [Azure/Microsoft.Extensions.Caching.Cosmos#15]
Regarding this line:

https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/src/CosmosCache.cs#L104

```cs
try
{
    await this.cosmosContainer.ReplaceItemAsync(
            partitionKey: new PartitionKey(key),
            id: key,
            item: cosmosCacheSessionResponse.Resource,
            requestOptions: new ItemRequestOptions()
            {
                IfMatchEtag = cosmosCacheSessionResponse.ETag,
            },
            cancellationToken: token).ConfigureAwait(false);
}
catch (CosmosException cosmosException) when (cosmosException.StatusCode == HttpStatusCode.PreconditionFailed)
{
    // Race condition on replace, we need to get the latest version of the item
    return await this.GetAsync(key, token).ConfigureAwait(false);
}
```

I assume the reason for this is to reset the ttl on every read access. This may make sense for session state but maybe not non-session related caching, such as application data you want cached for one minute or one hour regardless of reads when using the IDistributedCache directly and not through the HTTP session.

Suggested enhancement:
```cs
cosmosCacheOptions.ResetTimeToLiveOnRead = false;
```

This also comes with a big performance hit of sending the cached data back to the server on every access for no reason other than to reset the ttl which would more than double the overall operation time as writes/indexing are slower than reads, correct me if I'm wrong. It's a shame Cosmos doesn't offer a specific ttl reset operation or even better to reset the ttl on a read with an optional parameter.

Am I wrong in the above?

Also, would love this as a Nuget package as well!

**Comment by krispenner** [comment]
Actually, thinking through this some more it would be great to support this per item and base this off the `DistributedCacheEntryOptions` which aligns the use with the intention of `DistributedCacheEntryOptions.AbsoluteExpiration`.

If you add a `IsSlidingExpiration` property to the session item, you could than use that to determine if the time to live should be updated via the `ReplaceItem` call or not during a read.

Suggestion:
```cs
    internal class CosmosCacheSession
    {
        [JsonProperty("id")]
        public string SessionKey { get; set; }

        [JsonProperty("content")]
        public byte[] Content { get; set; }

        [JsonProperty("ttl")]
        public long? TimeToLive { get; set; }

        // True if DistributedCacheEntryOptions.AbsoluteExpiration was set and used for the TTL,
        // false if DistributedCacheEntryOptions.AbsoluteExpiration or DistributedCacheEntryOptions.AbsoluteExpirationRelativeToNow was set and used for the TTL;
        // otherwise null.
        [JsonProperty("isSlidingExpiration")]
        public bool? IsSlidingExpiration { get; set; }
    }
```

Set the `IsSlidingExpiration` property based on whether the `DistributedCacheEntryOptions.SlidingExpiration` was used or not. See comments on the `IsSlidingExpiration` property code snippet above.

Then only replace the item during a read if `IsSlidingExpiration` is `true`:

```cs
if (cosmosCacheSessionResponse.Resource.IsSlidingExpiration.GetValueOrDefault())
{
    try
    {
        await this.cosmosContainer.ReplaceItemAsync(
                partitionKey: new PartitionKey(key),
                id: key,
                item: cosmosCacheSessionResponse.Resource,
                requestOptions: new ItemRequestOptions()
                {
                    IfMatchEtag = cosmosCacheSessionResponse.ETag,
                },
                cancellationToken: token).ConfigureAwait(false);
    }
    catch (CosmosException cosmosException) when (cosmosException.StatusCode == HttpStatusCode.PreconditionFailed)
    {
        // Race condition on replace, we need to get the latest version of the item
        return await this.GetAsync(key, token).ConfigureAwait(false);
    }
}
```

I hope that makes sense, this would then better support both `AbsoluteExpiration` and `SlidingExpiration` that the `DistributedCacheEntryOptions` exposes.

If there was another reason for the `ReplaceItem` call other than to reset the ttl, then maybe all this is irrelevant. Looking forward to your thoughts.

**Comment by krispenner** [comment]
See above PR, hope I did that right as I haven't done to many PRs on here. Let me know if that makes sense and is useful. Cheers!

**Comment by ealsur** [comment]
Thanks for the contribution @krispenner !

The original intent was not about the TTL but the Timestamp. In order for SlidingExpiration to really work, the Replace updates the item and thus the Timestamp (_ts) property is updated, so TTL can act accordingly.

I'll check the PR out.

**Comment by krispenner** [comment]
Ah sorry, you are correct and I meant to say timestamp (_ts) everywhere I said TTL. 

However, my primary point still stands, the current code always forces sliding expiration even when `DistributedCacheEntryOptions.AbsoluteExpiration` is used for the item's expiry. 

My PR should address this and only use sliding expiration (by updating _ts via ReplaceItem) when `DistributedCacheEntryOptions.SlidingExpiration` is used for the item's expiry, otherwise it will expire at the set absolute time if `DistributedCacheEntryOptions.AbsoluteExpiration` or `DistributedCacheEntryOptions.AbsoluteExpirationRelativeToNow` is used instead regardless of any reads on the item or not.

Thanks for your consideration and any feedback :)

**Comment by ealsur** [comment]
I left comments in the PR 😄
