### ISSUE TITLE
During GetAsync, retrying causes cascading PreconditionFailed errors

### ISSUE THREAD

**Issue by rhofstra-sefi** [Azure/Microsoft.Extensions.Caching.Cosmos#27]
Somewhat related to https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/issues/15#issue-543549307.

For high touch cache items that are read often, I'm running into problems where that item fails the ttl update call repeatedly since it is being read (and then updated) so much.  It seems that failing an update just to reset the ttl probably isn't worthy of retrying the get.  For cache items that aren't critical, it would be beneficial to be able to configure whether that retry should occur.

@ealsur Any objection to adding this functionality?

**Comment by ealsur** [comment]
The PR was merged that doesn't do the update if you use AbsoluteExpiration, are you using AbsoluteExpiration? https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/pull/16

**Comment by rhofstra-sefi** [comment]
We want to use sliding expiration, we just have some cache items that are touched often enough that retrying if the ttl update fails causes problems.  I'd like to add an option to make just the retry configurable.

**Comment by ealsur** [comment]
Which would be the logic to determine when to do the update? Would the configuration be at the item level? What if the update doesn't happen (due to the configuration) and the item is evicted?

Could you propose what your configuration would look like and how it would work on different scenarios? A PR or some code here would work.

**Comment by rhofstra-sefi** [comment]
That would be the reason it would be configurable.  For applications that need to ensure the update occurs, the default would still be to retry.  However, for applications that are constantly touching a cache item, especially when there are hundreds of reads to every write, allowing each read to do a fire-and-forget type update prevents this kind of deadlock.  The applications that care more about cache speed than the occasional dropped cache item can operate trusting the volume of requests to keep the sliding window active.

I'll put in a PR, I just wanted to run the idea by you first.  It should be fairly simple, just another bool (RetrySlidingTTLUpdate?) that defaults true and 
`                catch (CosmosException cosmosException) when (cosmosException.StatusCode == HttpStatusCode.PreconditionFailed)
                {
                    **if (RetrySlidingTTLUpdate) {**
                        // Race condition on replace, we need to get the latest version of the item
                        return await this.GetAsync(key, token).ConfigureAwait(false);
                    }
                }`

**Comment by ealsur** [comment]
I see, my only concern is with naming. I guess this would be an option in https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/src/CosmosCacheOptions.cs, but which would be a name that would convey which scenarios would a user would want to use it (something self explanatory to avoid misuse).

**Comment by rhofstra-sefi** [comment]
Yes, "RetrySlidingTTLUpdate" isn't the easiest to understand, I'll work on coming up with something better.  As far as which should be the default, I think the current behavior could stay default, just to guarantee it works the more stable way for those who aren't configuring the options, while those who intend to take the risk of not guaranteeing updates can choose to.
