### ISSUE TITLE
Chaining SlidingExpiration and AbsoluteExpiration

### ISSUE THREAD

**Issue by mwgustin** [Azure/Microsoft.Extensions.Caching.Cosmos#32]
Hello,

Great work on this implementation so far. Excited to start using this in our projects.

As I was testing I came across an issue though.  If you use both a SlidingExpiration with an AbsoluteExpiration, (ie I want to slide the expiration ever minute to an absolute maximum of 10 minutes), the current implementation only obeys the sliding expiration. 

```
var cacheOpts = new DistributedCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromMinutes(1)).SetAbsoluteExpiration(TimeSpan.FromMinutes(10));
```

My initial suggestion is to continue using the TTL for the slidingExpiration, but add a field to store absolute expiration's timestamp... then whenever refreshing the TTL for the sliding expiration on a GET, do a calculation to determine if the sliding expiration TTL is greater than the absolute expiration... if it is, then use the remaining time for the absolute expiration as the TTL instead.

For sliding Expirations, the TTL will just naturally expire, but for any that come within the bounds of the Absolute Expiration will have the TTL overridden by the value for the Absolute Expiration.

**Comment by ealsur** [comment]
@mwgustin see https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/pull/33, if you can validate that the branch solves your problem, I can work on a merge and release

**Comment by mwgustin** [comment]
@ealsur Wow! What a quick turn around. I was gonna take a stab at it later this week, but you knocked it out of the park. 

This worked perfectly. Thanks!

**Comment by ealsur** [comment]
Thanks for the confirmation, will move forward with the release.

**Comment by ealsur** [comment]
@mwgustin The feature was released in preview5 https://www.nuget.org/packages/Microsoft.Extensions.Caching.Cosmos/1.0.0-preview5

**Comment by mwgustin** [comment]
Stellar work! Thanks again for getting this implemented and updated so quickly.
