### ISSUE TITLE
The ID for the cosmos cache entry is a random string instead of the account identifier when using AquireTokenOnBehalfOf

### ISSUE THREAD

**Issue by SirElTomato** [Azure/Microsoft.Extensions.Caching.Cosmos#39]
When using AquireTokenByAuthorisationCode the id of the cosmos cache entry is the account identifier (objectId.tenantId). Then when I call AcquireTokenSilent the token is successfully retrieved from the cache. 

However when using AquireTokenOnBehalfOf the id of the cosmos cache entry is (what looks like) a random string e.g. "JwCRE_PxyK4t2A76iuST6W_jewmNE-1epMH8yAXFPMg" or "DpUHeYQg5xT52Tdk62t_shU5m1Lm2BIVkbhQ6EtzucE". The rest of the cache entry looks correct. Then when I call AcquireTokenSilent, the retrieval fails with "No Refresh Token found in the cache", which makes sense since it is trying to use the account identifier to retrieve the token from the cache but that account identifier doesnt exist. 

Is this a bug or is it saving the tokens with a different ID for a reason?

**Comment by ealsur** [comment]
@SirElTomato the code in this extension does not generate the key, the key is passed as input: https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/src/CosmosCache.cs#L240, based on the `IDistributedCache` interface.

**Comment by SirElTomato** [comment]
For anyone else that has this issue, see issue mentioned above for how I fixed this.
