### ISSUE TITLE
MSAL OBO flow is unable to retrieve tokens from the cache after an hour has elapsed. 

### ISSUE THREAD

**Issue by SirElTomato** [Azure/Microsoft.Extensions.Caching.Cosmos#49]
**Describe the bug**
MSAL OBO flow is unable to retrieve tokens from the cache after an hour has elapsed. 

See issue described [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2558).
Specific comment [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2558#issuecomment-899603028)

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by ealsur** [comment]
@SirElTomato What are the errors happening on this particular cache extension? The cache operations either succeed or fail. The error in those links does not have a call stack that matches this extension.

**Comment by SirElTomato** [comment]
The cosmos container is emptying after an elapsed period of time, possibly 90 minutes. Is there something I need to set to stop this from happening?

**Comment by ealsur** [comment]
@SirElTomato Cosmos container being empty either means the documents are being deleted or TTL is enabled.

If you created the Container manually, what was the TTL defined? If you did not, and let the library create it for you through the `CreateIfNotExists` flag, the container is created with a TTL based off the `CosmosCacheOptions.DefaultTimeToLiveInMs` value, if that is not set, then it uses a default value of `-1` meaning the items do not expire by default: https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/src/CosmosCache.cs#L402-L403

If the TTL in the container is `-1` (meaning enabled but nothing expiring by default) and the items are going away, the only other possibility is that the cache entries have an individual expiration being set.

Are you configuring the options with Sliding and/or Absolute expiration on the items?

**Comment by SirElTomato** [comment]
@ealsur There was a TTL value set. I've set it to off now so hopefully that does it, thanks!
