### ISSUE TITLE
Error message should say 'content' instead of 'id'.

### ISSUE THREAD

**Issue by krispenner** [Azure/Microsoft.Extensions.Caching.Cosmos#61]
https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/af97b05ef282baf98393911bdf8ffc8c4dbae6ff/src/CosmosCacheSessionConverter.cs#L46

**Comment by ealsur** [comment]
@krispenner Is this fix needed on a hotfix release?

**Comment by krispenner** [comment]
@ealsur Nope, just noticed it while browsing the source code :)
