### ISSUE TITLE
Support retrieving TTL for GET

### ISSUE THREAD

**Issue by Harshan01** [Azure/Microsoft.Extensions.Caching.Cosmos#70]
**Is your feature request related to a problem? Please describe.**
The feature request describes retrieving the TTL info from Cosmos for use in application layer, or an intermediate memory cache between application layer and Cosmos cache. Use of intermediate cache without TTL results in maximum of 2 times TTL when populating the memory cache from Cosmos.

**Describe the solution you'd like**
Expose a custom API `CosmosCache.GetWithTTL(string key)` which is not a part of IDistributedCache, which returns an object with `Value/Content` and `RemainingTTL`.

**Describe alternatives you've considered**
Implementing a util method in application layer, but it is desirable to have this feature in the caching layer

**Additional context**
N/A

**Comment by ealsur** [comment]
@Harshan01 In Cosmos DB, the TTL is not the remaining, it is simply the value, in seconds after which the item is deleted by the system. The system makes the calculation of the time left, the time left is not part of the information present in the document.

Producing something called "RemainingTTL" is not possible, we could just return the TTL but the TTL is the value configured on the Caching configuration. We could return the raw document but it would be on your application logic to do the calculation, at that point, you are also having to write your custom code though, it won't eliminate the need to have some custom code somewhere.
